name: Flutter Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Fix Dependencies
        run: |
          flutter clean
          flutter pub upgrade
        working-directory: material_3_demo

      - name: Build APK (Ignore Warnings)
        run: |
          # Yeh command Kotlin errors ko minimize karne ke liye hai
          flutter build apk --release --no-pub --target-platform android-arm64
        working-directory: material_3_demo

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: star-chat-app
          path: material_3_demo/build/app/outputs/flutter-apk/app-release.apk
