name: Flutter Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Yeh version aapki SDK shart ko poora karega
          channel: 'stable'

      - name: Force Clean Build
        run: |
          flutter clean
          flutter pub get
        working-directory: material_3_demo

      - name: Build APK (Stable)
        run: flutter build apk --release --no-tree-shake-icons
        working-directory: material_3_demo

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: star-chat-final-app
          path: material_3_demo/build/app/outputs/flutter-apk/app-release.apk
